{{- $ingress := .Values.Proxy.Ingress -}}
{{- $fullName := include "spark.ui-proxy-fullname" . -}}
{{- if $ingress.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "spark.ui-proxy-fullname" . }}
{{- if $ingress.Annotations }}
  annotations:
{{ toYaml $ingress.Annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    {{- include "spark.proxyLabels" . | nindent 4 }}
spec:
{{- if $ingress.Tls }}
  tls:
  - hosts:
    - {{ .Values.Proxy.Ingress.Host }}
    secretName: {{ .SecretName | default (printf "%s-tls" $fullName) }}
{{- end }}
  rules:
  - host: {{ .Values.Proxy.Ingress.Host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "spark.ui-proxy-fullname" . }}
          servicePort: {{ include "spark.ingress.port" $ }}
{{- end }}
