apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.master-fullname" . }}-headless
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    {{- include "spark.masterLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"