apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.ui-proxy-fullname" . }}
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    {{- include "spark.proxyLabels" . | nindent 4 }}
  {{- if .Values.Proxy.service.annotations }}
  annotations: {{ .Values.Proxy.service.annotations| nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.Proxy.service.type }}
  ports:
    - port: {{ .Values.Proxy.service.port }}
      targetPort: {{ .Values.Proxy.containerPort }}
  selector: 
    component: "{{ .Release.Name }}-{{ .Values.Proxy.component }}"