{{- if .Values.Worker.Autoscaling.Enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    {{- include "spark.workerLabels" . | nindent 4 }}
  name: {{ template "spark.worker-fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: {{ template "spark.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "spark.worker-fullname" . }}
  minReplicas: {{ .Values.Worker.Replicas }}
  maxReplicas: {{ .Values.Worker.ReplicasMax }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.Worker.CpuTargetPercentage }}
{{- end }}
