{{- $ingress := .Values.Proxy.Ingress -}}
{{- $fullName := include "ui-proxy-fullname" . -}}
{{- if $ingress.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui-proxy-fullname" . }}
{{- if $ingress.Annotations }}
  annotations:
{{ toYaml $ingress.Annotations | indent 4 }}
{{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Proxy.component }}"
spec:
{{- if $ingress.Tls }}
  tls:
  {{- range $ingress.Tls }}
  - hosts:
    {{- range .Hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .SecretName | default (printf "%s-tls" $fullName) }}
{{- end }}
{{- end }}
  {{- if $ingress.Hosts }}
  rules:
  {{- range $ingress.Hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $ingress.Path }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: http
  {{- end }}
{{- else }}
  backend:
    serviceName: {{ template "ui-proxy-fullname" . }}
    servicePort: http
{{- end }}
{{- end }}
