apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.proxy.service.name" $ }}
  labels: {{- include "spark.labels" . | nindent 4 }}
  {{- if .Values.proxy.service.annotations }}
  annotations: {{- include "spark.tplValue" ( dict "value" .Values.proxy.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: {{ .Values.proxy.containerPort }}
  selector: {{- include "spark.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui-proxy
